# adapted from:
#   https://www.rohanjain.in/cargo-cross/
#   https://github.com/crodjer/sysit/blob/v0.4.0/.github/workflows/release.yml

name: Build

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-crate:
    name: Build Crate
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.rustup
          target
        key: ${{ runner.os }}-stable
    - name: Setup
      run: |
        rustup install stable
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test
#     - name: Publish
#       run: cargo publish
#       env:
#         CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
